### ISSUE TITLE
Cannot destructure property 'title' of 'collection' as it is undefined

### ISSUE THREAD

**Issue by aboubacarmsr** [ZhangMYihua/lesson-23#4]
Hello everyone

I have a "Cannot destructure property 'title' of 'collection' as it is undefined" issue with this lesson, it seems like my mapStateToProps function in Collection.components.jsx returns an empty value

`const mapStateToProps = (state, ownProps) => ({
    collection: selectCollection(ownProps.match.params.collectionId)(state)
});`

Can anyone please help me ?

**Comment by kamaldobriyalkd** [comment]
Actually I am also facing this issue please help me.

**Comment by aboubacarmsr** [comment]
Check that the category names and links url in your dummy data (shop.data.js & directory.reducer.js) are the same in your Firebase ;)
