### ISSUE TITLE
Issue with property title of collection cannot be destructured

### ISSUE THREAD

**Issue by kamaldobriyalkd** [ZhangMYihua/lesson-23#7]
Hello everybody

My app is causing "Cannot destructure property 'title' of 'collection' as it is undefined" issue, it seems like the mapStateToProps function in Collection.components.jsx returns an empty value

const mapStateToProps = (state, ownProps) => ({ collection: selectCollection(ownProps.match.params.collectionId)(state) });

please help me out.

**Comment by custom1415** [comment]
how to fix
 this issue?
